CREATE TABLE [dbo].[Matches]
(
	[MatchId] INT PRIMARY KEY IDENTITY (1, 1) NOT NULL, 
    [TournamentId] INT NOT NULL, 
    [ChiefRefereeId] INT NOT NULL, 
    [LeftLinesmanId] INT NOT NULL, 
    [RightLinesmanId] INT NOT NULL, 
    [ReserveRefereeId] INT NOT NULL, 
    [VARId] INT NOT NULL, 
    [VARAssistantId] INT NOT NULL, 
    [FC1Id] INT NOT NULL, 
    [FC2Id] INT NOT NULL, 
    [CountGoalsFC1] TINYINT NOT NULL, 
    [CountGoalsFC2] TINYINT NOT NULL, 
    [CoachFC1Id] INT NOT NULL, 
    [CoachFC2Id] INT NOT NULL, 
    [KeeperFC1Id] INT NOT NULL, 
    [CountMinKeeperFC1] TINYINT NOT NULL, 
    [CountMissedGoalKeeperFC1] TINYINT NOT NULL, 
    [CountScoredGoalKeeperFC1] TINYINT NOT NULL, 
    [CountScoredAutogoalKeeperFC1] TINYINT NOT NULL,
    [CountAssistKeeperFC1] TINYINT NOT NULL, 
    [CountYellowCardKeeperFC1] TINYINT NOT NULL, 
    [CountRedCardKeeperFC1] BIT NOT NULL, 
    [Fielder1FC1Id] INT NOT NULL, 
    [CountMinFielder1FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder1FC1] TINYINT NOT NULL, 
    [CountAssistFielder1FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder1FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder1FC1] TINYINT NOT NULL, 
    [CountRedCardFielder1FC1] BIT NOT NULL, 
    [Fielder2FC1Id] INT NOT NULL, 
    [CountMinFielder2FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder2FC1] TINYINT NOT NULL, 
    [CountAssistFielder2FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder2FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder2FC1] TINYINT NOT NULL, 
    [CountRedCardFielder2FC1] BIT NOT NULL, 
    [Fielder3FC1Id] INT NOT NULL, 
    [CountMinFielder3FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder3FC1] TINYINT NOT NULL, 
    [CountAssistFielder3FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder3FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder3FC1] TINYINT NOT NULL, 
    [CountRedCardFielder3FC1] BIT NOT NULL, 
    [Fielder4FC1Id] INT NOT NULL, 
    [CountMinFielder4FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder4FC1] TINYINT NOT NULL, 
    [CountAssistFielder4FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder4FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder4FC1] TINYINT NOT NULL, 
    [CountRedCardFielder4FC1] BIT NOT NULL, 
    [Fielder5FC1Id] INT NOT NULL, 
    [CountMinFielder5FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder5FC1] TINYINT NOT NULL, 
    [CountAssistFielder5FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder5FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder5FC1] TINYINT NOT NULL, 
    [CountRedCardFielder5FC1] BIT NOT NULL, 
    [Fielder6FC1Id] INT NOT NULL, 
    [CountMinFielder6FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder6FC1] TINYINT NOT NULL, 
    [CountAssistFielder6FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder6FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder6FC1] TINYINT NOT NULL, 
    [CountRedCardFielder6FC1] BIT NOT NULL, 
    [Fielder7FC1Id] INT NOT NULL, 
    [CountMinFielder7FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder7FC1] TINYINT NOT NULL, 
    [CountAssistFielder7FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder7FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder7FC1] TINYINT NOT NULL, 
    [CountRedCardFielder7FC1] BIT NOT NULL, 
    [Fielder8FC1Id] INT NOT NULL, 
    [CountMinFielder8FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder8FC1] TINYINT NOT NULL, 
    [CountAssistFielder8FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder8FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder8FC1] TINYINT NOT NULL, 
    [CountRedCardFielder8FC1] BIT NOT NULL, 
    [Fielder9FC1Id] INT NOT NULL, 
    [CountMinFielder9FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder9FC1] TINYINT NOT NULL, 
    [CountAssistFielder9FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder9FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder9FC1] TINYINT NOT NULL, 
    [CountRedCardFielder9FC1] BIT NOT NULL, 
    [Fielder10FC1Id] INT NOT NULL, 
    [CountMinFielder10FC1] TINYINT NOT NULL, 
    [CountScoredGoalFielder10FC1] TINYINT NOT NULL, 
    [CountAssistFielder10FC1] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder10FC1] TINYINT NOT NULL, 
    [CountYellowCardFielder10FC1] TINYINT NOT NULL, 
    [CountRedCardFielder10FC1] BIT NOT NULL, 
    [Reserve1FC1Id] INT NULL, 
    [CountMissedGoalReserveKeeper1FC1] TINYINT NULL, 
    [CountMinReserve1FC1] TINYINT NULL, 
    [CountScoredGoalReserve1FC1] TINYINT NULL, 
    [CountAssistReserve1FC1] TINYINT NULL, 
    [CountScoredAutogoalReserve1FC1] TINYINT NULL, 
    [CountYellowCardReserve1FC1] TINYINT NULL, 
    [CountRedCardReserve1FC1] BIT NULL, 
    [Reserve2FC1Id] INT NULL, 
    [CountMissedGoalReserveKeeper2FC1] TINYINT NULL, 
    [CountMinReserve2FC1] TINYINT NULL, 
    [CountScoredGoalReserve2FC1] TINYINT NULL, 
    [CountAssistReserve2FC1] TINYINT NULL, 
    [CountScoredAutogoalReserve2FC1] TINYINT NULL, 
    [CountYellowCardReserve2FC1] TINYINT NULL, 
    [CountRedCardReserve2FC1] BIT NULL, 
    [Reserve3FC1Id] INT NULL, 
    [CountMissedGoalReserveKeeper3FC1] TINYINT NULL, 
    [CountMinReserve3FC1] TINYINT NULL, 
    [CountScoredGoalReserve3FC1] TINYINT NULL, 
    [CountAssistReserve3FC1] TINYINT NULL, 
    [CountScoredAutogoalReserve3FC1] TINYINT NULL, 
    [CountYellowCardReserve3FC1] TINYINT NULL, 
    [CountRedCardReserve3FC1] BIT NULL, 
    [KeeperFC2Id] INT NOT NULL, 
    [CountMinKeeperFC2] TINYINT NOT NULL, 
    [CountMissedGoalKeeperFC2] TINYINT NOT NULL, 
    [CountScoredGoalKeeperFC2] TINYINT NOT NULL, 
    [CountScoredAutogoalKeeperFC2] TINYINT NOT NULL,
    [CountAssistKeeperFC2] TINYINT NOT NULL, 
    [CountYellowCardKeeperFC2] TINYINT NOT NULL, 
    [CountRedCardKeeperFC2] BIT NOT NULL, 
    [Fielder1FC2Id] INT NOT NULL, 
    [CountMinFielder1FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder1FC2] TINYINT NOT NULL, 
    [CountAssistFielder1FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder1FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder1FC2] TINYINT NOT NULL, 
    [CountRedCardFielder1FC2] BIT NOT NULL, 
    [Fielder2FC2Id] INT NOT NULL, 
    [CountMinFielder2FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder2FC2] TINYINT NOT NULL, 
    [CountAssistFielder2FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder2FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder2FC2] TINYINT NOT NULL, 
    [CountRedCardFielder2FC2] BIT NOT NULL, 
    [Fielder3FC2Id] INT NOT NULL, 
    [CountMinFielder3FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder3FC2] TINYINT NOT NULL, 
    [CountAssistFielder3FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder3FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder3FC2] TINYINT NOT NULL, 
    [CountRedCardFielder3FC2] BIT NOT NULL, 
    [Fielder4FC2Id] INT NOT NULL, 
    [CountMinFielder4FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder4FC2] TINYINT NOT NULL, 
    [CountAssistFielder4FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder4FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder4FC2] TINYINT NOT NULL, 
    [CountRedCardFielder4FC2] BIT NOT NULL, 
    [Fielder5FC2Id] INT NOT NULL, 
    [CountMinFielder5FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder5FC2] TINYINT NOT NULL, 
    [CountAssistFielder5FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder5FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder5FC2] TINYINT NOT NULL, 
    [CountRedCardFielder5FC2] BIT NOT NULL, 
    [Fielder6FC2Id] INT NOT NULL, 
    [CountMinFielder6FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder6FC2] TINYINT NOT NULL, 
    [CountAssistFielder6FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder6FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder6FC2] TINYINT NOT NULL, 
    [CountRedCardFielder6FC2] BIT NOT NULL, 
    [Fielder7FC2Id] INT NOT NULL, 
    [CountMinFielder7FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder7FC2] TINYINT NOT NULL, 
    [CountAssistFielder7FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder7FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder7FC2] TINYINT NOT NULL, 
    [CountRedCardFielder7FC2] BIT NOT NULL, 
    [Fielder8FC2Id] INT NOT NULL, 
    [CountMinFielder8FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder8FC2] TINYINT NOT NULL, 
    [CountAssistFielder8FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder8FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder8FC2] TINYINT NOT NULL, 
    [CountRedCardFielder8FC2] BIT NOT NULL, 
    [Fielder9FC2Id] INT NOT NULL, 
    [CountMinFielder9FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder9FC2] TINYINT NOT NULL, 
    [CountAssistFielder9FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder9FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder9FC2] TINYINT NOT NULL, 
    [CountRedCardFielder9FC2] BIT NOT NULL, 
    [Fielder10FC2Id] INT NOT NULL, 
    [CountMinFielder10FC2] TINYINT NOT NULL, 
    [CountScoredGoalFielder10FC2] TINYINT NOT NULL, 
    [CountAssistFielder10FC2] TINYINT NOT NULL, 
    [CountScoredAutogoalFielder10FC2] TINYINT NOT NULL, 
    [CountYellowCardFielder10FC2] TINYINT NOT NULL, 
    [CountRedCardFielder10FC2] BIT NOT NULL, 
    [Reserve1FC2Id] INT NULL, 
    [CountMissedGoalReserveKeeper1FC2] TINYINT NULL, 
    [CountMinReserve1FC2] TINYINT NULL, 
    [CountScoredGoalReserve1FC2] TINYINT NULL, 
    [CountAssistReserve1FC2] TINYINT NULL, 
    [CountScoredAutogoalReserve1FC2] TINYINT NULL, 
    [CountYellowCardReserve1FC2] TINYINT NULL, 
    [CountRedCardReserve1FC2] BIT NULL, 
    [Reserve2FC2Id] INT NULL, 
    [CountMissedGoalReserveKeeper2FC2] TINYINT NULL, 
    [CountMinReserve2FC2] TINYINT NULL, 
    [CountScoredGoalReserve2FC2] TINYINT NULL, 
    [CountAssistReserve2FC2] TINYINT NULL, 
    [CountScoredAutogoalReserve2FC2] TINYINT NULL, 
    [CountYellowCardReserve2FC2] TINYINT NULL, 
    [CountRedCardReserve2FC2] BIT NULL, 
    [Reserve3FC2Id] INT NULL, 
    [CountMissedGoalReserveKeeper3FC2] TINYINT NULL, 
    [CountMinReserve3FC2] TINYINT NULL, 
    [CountScoredGoalReserve3FC2] TINYINT NULL, 
    [CountAssistReserve3FC2] TINYINT NULL, 
    [CountScoredAutogoalReserve3FC2] TINYINT NULL, 
    [CountYellowCardReserve3FC2] TINYINT NULL, 
    [CountRedCardReserve3FC2] BIT NULL, 
    CONSTRAINT [FK_Matches_Tournaments] FOREIGN KEY ([TournamentId]) REFERENCES [Tournaments]([TournamentId]), 
    CONSTRAINT [FK_Matches_Referees1] FOREIGN KEY ([ChiefRefereeId]) REFERENCES [Referees]([RefereeId]), 
    CONSTRAINT [FK_Matches_Referees2] FOREIGN KEY ([LeftLinesmanId]) REFERENCES [Referees]([RefereeId]), 
    CONSTRAINT [FK_Matches_Referees3] FOREIGN KEY ([RightLinesmanId]) REFERENCES [Referees]([RefereeId]), 
    CONSTRAINT [FK_Matches_Referees4] FOREIGN KEY ([ReserveRefereeId]) REFERENCES [Referees]([RefereeId]), 
    CONSTRAINT [FK_Matches_Referees5] FOREIGN KEY ([VARId]) REFERENCES [Referees]([RefereeId]), 
    CONSTRAINT [FK_Matches_Referees6] FOREIGN KEY ([VARAssistantId]) REFERENCES [Referees]([RefereeId]), 
    CONSTRAINT [FK_Matches_FootballClubs1] FOREIGN KEY ([FC1Id]) REFERENCES [FootballClubs]([FCId]), 
    CONSTRAINT [FK_Matches_FootballClubs2] FOREIGN KEY ([FC2Id]) REFERENCES [FootballClubs]([FCId]), 
    CONSTRAINT [FK_Matches_Coaches1] FOREIGN KEY ([CoachFC1Id]) REFERENCES [Coaches]([CoachId]), 
    CONSTRAINT [FK_Matches_Coaches2] FOREIGN KEY ([CoachFC2Id]) REFERENCES [Coaches]([CoachId]), 
    CONSTRAINT [FK_Matches_Players1] FOREIGN KEY ([KeeperFC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players2] FOREIGN KEY ([Fielder1FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players3] FOREIGN KEY ([Fielder2FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players4] FOREIGN KEY ([Fielder3FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players5] FOREIGN KEY ([Fielder4FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players6] FOREIGN KEY ([Fielder5FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players7] FOREIGN KEY ([Fielder6FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players8] FOREIGN KEY ([Fielder7FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players9] FOREIGN KEY ([Fielder8FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players10] FOREIGN KEY ([Fielder9FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players11] FOREIGN KEY ([Fielder10FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players12] FOREIGN KEY ([Reserve1FC1Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players13] FOREIGN KEY ([Reserve2FC1Id]) REFERENCES [Players]([PlayerId]),
    CONSTRAINT [FK_Matches_Players14] FOREIGN KEY ([Reserve3FC1Id]) REFERENCES [Players]([PlayerId]),
    CONSTRAINT [FK_Matches_Players15] FOREIGN KEY ([KeeperFC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players16] FOREIGN KEY ([Fielder1FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players17] FOREIGN KEY ([Fielder2FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players18] FOREIGN KEY ([Fielder3FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players19] FOREIGN KEY ([Fielder4FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players20] FOREIGN KEY ([Fielder5FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players21] FOREIGN KEY ([Fielder6FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players22] FOREIGN KEY ([Fielder7FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players23] FOREIGN KEY ([Fielder8FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players24] FOREIGN KEY ([Fielder9FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players25] FOREIGN KEY ([Fielder10FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players26] FOREIGN KEY ([Reserve1FC2Id]) REFERENCES [Players]([PlayerId]), 
    CONSTRAINT [FK_Matches_Players27] FOREIGN KEY ([Reserve2FC2Id]) REFERENCES [Players]([PlayerId]),
    CONSTRAINT [FK_Matches_Players28] FOREIGN KEY ([Reserve3FC2Id]) REFERENCES [Players]([PlayerId])
)