CREATE PROCEDURE [dbo].[Insert_Match]
	@tournamentId INT,
	@chiefRefereeId INT,
	@leftLinesmanId INT,
	@rightLinesmanId INT,
	@reserveRefereeId INT,
	@varId INT,
	@varAssistantId INT,
	@fc1Id INT,
	@fc2Id INT,
	@countGoalsFC1 TINYINT,
	@countGoalsFC2 TINYINT,
	@coachFC1Id INT,
	@coachFC2Id INT,
	@keeperFC1Id INT,
	@countMinKeeperFC1 TINYINT,
	@countMissedGoalKeeperFC1 TINYINT,
	@countScoredGoalKeeperFC1 TINYINT,
	@countScoredAutogoalKeeperFC1 TINYINT,
	@countAssistKeeperFC1 TINYINT,
	@countYellowCardKeeperFC1 TINYINT,
	@countRedCardKeeperFC1 BIT,
	@fielder1FC1Id INT,
	@countMinFielder1FC1 TINYINT,
	@countScoredGoalFielder1FC1 TINYINT,
	@countAssistFielder1FC1 TINYINT,
	@countScoredAutogoalFielder1FC1 TINYINT,
	@countYellowCardFielder1FC1 TINYINT,
	@countRedCardFielder1FC1 BIT,
	@fielder2FC1Id INT,
	@countMinFielder2FC1 TINYINT,
	@countScoredGoalFielder2FC1 TINYINT,
	@countAssistFielder2FC1 TINYINT,
	@countScoredAutogoalFielder2FC1 TINYINT,
	@countYellowCardFielder2FC1 TINYINT,
	@countRedCardFielder2FC1 BIT,
	@fielder3FC1Id INT,
	@countMinFielder3FC1 TINYINT,
	@countScoredGoalFielder3FC1 TINYINT,
	@countAssistFielder3FC1 TINYINT,
	@countScoredAutogoalFielder3FC1 TINYINT,
	@countYellowCardFielder3FC1 TINYINT,
	@countRedCardFielder3FC1 BIT,
	@fielder4FC1Id INT, 
    @countMinFielder4FC1 TINYINT, 
    @countScoredGoalFielder4FC1 TINYINT, 
    @countAssistFielder4FC1 TINYINT, 
    @countScoredAutogoalFielder4FC1 TINYINT, 
    @countYellowCardFielder4FC1 TINYINT, 
    @countRedCardFielder4FC1 BIT, 
	@fielder5FC1Id INT, 
    @countMinFielder5FC1 TINYINT, 
    @countScoredGoalFielder5FC1 TINYINT, 
    @countAssistFielder5FC1 TINYINT, 
    @countScoredAutogoalFielder5FC1 TINYINT, 
    @countYellowCardFielder5FC1 TINYINT, 
    @countRedCardFielder5FC1 BIT, 
    @fielder6FC1Id INT, 
    @countMinFielder6FC1 TINYINT, 
    @countScoredGoalFielder6FC1 TINYINT, 
    @countAssistFielder6FC1 TINYINT, 
    @countScoredAutogoalFielder6FC1 TINYINT, 
    @countYellowCardFielder6FC1 TINYINT, 
    @countRedCardFielder6FC1 BIT, 
    @fielder7FC1Id INT, 
    @countMinFielder7FC1 TINYINT, 
    @countScoredGoalFielder7FC1 TINYINT, 
    @countAssistFielder7FC1 TINYINT, 
    @countScoredAutogoalFielder7FC1 TINYINT, 
    @countYellowCardFielder7FC1 TINYINT, 
    @countRedCardFielder7FC1 BIT,
	@fielder8FC1Id INT, 
    @countMinFielder8FC1 TINYINT, 
    @countScoredGoalFielder8FC1 TINYINT, 
    @countAssistFielder8FC1 TINYINT, 
    @countScoredAutogoalFielder8FC1 TINYINT, 
    @countYellowCardFielder8FC1 TINYINT, 
    @countRedCardFielder8FC1 BIT, 
    @fielder9FC1Id INT, 
    @countMinFielder9FC1 TINYINT, 
    @countScoredGoalFielder9FC1 TINYINT, 
    @countAssistFielder9FC1 TINYINT, 
    @countScoredAutogoalFielder9FC1 TINYINT, 
    @countYellowCardFielder9FC1 TINYINT, 
    @countRedCardFielder9FC1 BIT, 
    @fielder10FC1Id INT, 
    @countMinFielder10FC1 TINYINT, 
    @countScoredGoalFielder10FC1 TINYINT, 
    @countAssistFielder10FC1 TINYINT, 
    @countScoredAutogoalFielder10FC1 TINYINT, 
    @countYellowCardFielder10FC1 TINYINT, 
    @countRedCardFielder10FC1 BIT,
	@reserve1FC1Id INT, 
    @countMissedGoalReserveKeeper1FC1 TINYINT, 
    @countMinReserve1FC1 TINYINT, 
    @countScoredGoalReserve1FC1 TINYINT, 
    @countAssistReserve1FC1 TINYINT, 
    @countScoredAutogoalReserve1FC1 TINYINT, 
    @countYellowCardReserve1FC1 TINYINT, 
    @countRedCardReserve1FC1 BIT, 
    @reserve2FC1Id INT, 
    @countMissedGoalReserveKeeper2FC1 TINYINT, 
    @countMinReserve2FC1 TINYINT, 
    @countScoredGoalReserve2FC1 TINYINT, 
    @countAssistReserve2FC1 TINYINT, 
    @countScoredAutogoalReserve2FC1 TINYINT, 
    @countYellowCardReserve2FC1 TINYINT, 
    @countRedCardReserve2FC1 BIT, 
    @reserve3FC1Id INT, 
    @countMissedGoalReserveKeeper3FC1 TINYINT, 
    @countMinReserve3FC1 TINYINT, 
    @countScoredGoalReserve3FC1 TINYINT, 
    @countAssistReserve3FC1 TINYINT, 
    @countScoredAutogoalReserve3FC1 TINYINT, 
    @countYellowCardReserve3FC1 TINYINT, 
    @countRedCardReserve3FC1 BIT,
    @keeperFC2Id INT, 
    @countMinKeeperFC2 TINYINT, 
    @countMissedGoalKeeperFC2 TINYINT, 
    @countScoredGoalKeeperFC2 TINYINT, 
    @countScoredAutogoalKeeperFC2 TINYINT,
    @countAssistKeeperFC2 TINYINT, 
    @countYellowCardKeeperFC2 TINYINT, 
    @countRedCardKeeperFC2 BIT, 
    @fielder1FC2Id INT, 
    @countMinFielder1FC2 TINYINT, 
    @countScoredGoalFielder1FC2 TINYINT, 
    @countAssistFielder1FC2 TINYINT, 
    @countScoredAutogoalFielder1FC2 TINYINT, 
    @countYellowCardFielder1FC2 TINYINT, 
    @countRedCardFielder1FC2 BIT, 
    @fielder2FC2Id INT, 
    @countMinFielder2FC2 TINYINT, 
    @countScoredGoalFielder2FC2 TINYINT, 
    @countAssistFielder2FC2 TINYINT, 
    @countScoredAutogoalFielder2FC2 TINYINT, 
    @countYellowCardFielder2FC2 TINYINT, 
    @countRedCardFielder2FC2 BIT, 
    @fielder3FC2Id INT, 
    @countMinFielder3FC2 TINYINT, 
    @countScoredGoalFielder3FC2 TINYINT, 
    @countAssistFielder3FC2 TINYINT, 
    @countScoredAutogoalFielder3FC2 TINYINT, 
    @countYellowCardFielder3FC2 TINYINT, 
    @countRedCardFielder3FC2 BIT,
    @fielder4FC2Id INT, 
    @countMinFielder4FC2 TINYINT, 
    @countScoredGoalFielder4FC2 TINYINT, 
    @countAssistFielder4FC2 TINYINT, 
    @countScoredAutogoalFielder4FC2 TINYINT, 
    @countYellowCardFielder4FC2 TINYINT, 
    @countRedCardFielder4FC2 BIT, 
    @fielder5FC2Id INT, 
    @countMinFielder5FC2 TINYINT, 
    @countScoredGoalFielder5FC2 TINYINT, 
    @countAssistFielder5FC2 TINYINT, 
    @countScoredAutogoalFielder5FC2 TINYINT, 
    @countYellowCardFielder5FC2 TINYINT, 
    @countRedCardFielder5FC2 BIT, 
    @fielder6FC2Id INT, 
    @countMinFielder6FC2 TINYINT, 
    @countScoredGoalFielder6FC2 TINYINT, 
    @countAssistFielder6FC2 TINYINT, 
    @countScoredAutogoalFielder6FC2 TINYINT, 
    @countYellowCardFielder6FC2 TINYINT, 
    @countRedCardFielder6FC2 BIT, 
    @fielder7FC2Id INT, 
    @countMinFielder7FC2 TINYINT, 
    @countScoredGoalFielder7FC2 TINYINT, 
    @countAssistFielder7FC2 TINYINT, 
    @countScoredAutogoalFielder7FC2 TINYINT, 
    @countYellowCardFielder7FC2 TINYINT, 
    @countRedCardFielder7FC2 BIT, 
    @fielder8FC2Id INT, 
    @countMinFielder8FC2 TINYINT, 
    @countScoredGoalFielder8FC2 TINYINT, 
    @countAssistFielder8FC2 TINYINT, 
    @countScoredAutogoalFielder8FC2 TINYINT, 
    @countYellowCardFielder8FC2 TINYINT, 
    @countRedCardFielder8FC2 BIT, 
    @fielder9FC2Id INT, 
    @countMinFielder9FC2 TINYINT, 
    @countScoredGoalFielder9FC2 TINYINT, 
    @countAssistFielder9FC2 TINYINT, 
    @countScoredAutogoalFielder9FC2 TINYINT, 
    @countYellowCardFielder9FC2 TINYINT, 
    @countRedCardFielder9FC2 BIT, 
    @fielder10FC2Id INT, 
    @countMinFielder10FC2 TINYINT, 
    @countScoredGoalFielder10FC2 TINYINT, 
    @countAssistFielder10FC2 TINYINT, 
    @countScoredAutogoalFielder10FC2 TINYINT, 
    @countYellowCardFielder10FC2 TINYINT, 
    @countRedCardFielder10FC2 BIT, 
    @reserve1FC2Id INT, 
    @countMissedGoalReserveKeeper1FC2 TINYINT, 
    @countMinReserve1FC2 TINYINT, 
    @countScoredGoalReserve1FC2 TINYINT, 
    @countAssistReserve1FC2 TINYINT, 
    @countScoredAutogoalReserve1FC2 TINYINT, 
    @countYellowCardReserve1FC2 TINYINT, 
    @countRedCardReserve1FC2 BIT, 
    @reserve2FC2Id INT, 
    @countMissedGoalReserveKeeper2FC2 TINYINT, 
    @countMinReserve2FC2 TINYINT, 
    @countScoredGoalReserve2FC2 TINYINT, 
    @countAssistReserve2FC2 TINYINT, 
    @countScoredAutogoalReserve2FC2 TINYINT, 
    @countYellowCardReserve2FC2 TINYINT, 
    @countRedCardReserve2FC2 BIT, 
    @reserve3FC2Id INT, 
    @countMissedGoalReserveKeeper3FC2 TINYINT, 
    @countMinReserve3FC2 TINYINT, 
    @countScoredGoalReserve3FC2 TINYINT, 
    @countAssistReserve3FC2 TINYINT, 
    @countScoredAutogoalReserve3FC2 TINYINT, 
    @countYellowCardReserve3FC2 TINYINT, 
    @countRedCardReserve3FC2 BIT 
AS
BEGIN
	INSERT INTO Matches
    VALUES(@tournamentId,
	@chiefRefereeId,
	@leftLinesmanId,
	@rightLinesmanId,
	@reserveRefereeId,
	@varId,
	@varAssistantId,
	@fc1Id,
	@fc2Id,
	@countGoalsFC1,
	@countGoalsFC2,
	@coachFC1Id,
	@coachFC2Id,
	@keeperFC1Id,
	@countMinKeeperFC1,
	@countMissedGoalKeeperFC1,
	@countScoredGoalKeeperFC1,
	@countScoredAutogoalKeeperFC1,
	@countAssistKeeperFC1,
	@countYellowCardKeeperFC1,
	@countRedCardKeeperFC1,
	@fielder1FC1Id,
	@countMinFielder1FC1,
	@countScoredGoalFielder1FC1,
	@countAssistFielder1FC1,
	@countScoredAutogoalFielder1FC1,
	@countYellowCardFielder1FC1,
	@countRedCardFielder1FC1,
	@fielder2FC1Id,
	@countMinFielder2FC1,
	@countScoredGoalFielder2FC1,
	@countAssistFielder2FC1,
	@countScoredAutogoalFielder2FC1,
	@countYellowCardFielder2FC1,
	@countRedCardFielder2FC1,
	@fielder3FC1Id,
	@countMinFielder3FC1,
	@countScoredGoalFielder3FC1,
	@countAssistFielder3FC1,
	@countScoredAutogoalFielder3FC1,
	@countYellowCardFielder3FC1,
	@countRedCardFielder3FC1,
	@fielder4FC1Id, 
    @countMinFielder4FC1, 
    @countScoredGoalFielder4FC1, 
    @countAssistFielder4FC1, 
    @countScoredAutogoalFielder4FC1, 
    @countYellowCardFielder4FC1, 
    @countRedCardFielder4FC1, 
	@fielder5FC1Id, 
    @countMinFielder5FC1, 
    @countScoredGoalFielder5FC1, 
    @countAssistFielder5FC1, 
    @countScoredAutogoalFielder5FC1, 
    @countYellowCardFielder5FC1, 
    @countRedCardFielder5FC1, 
    @fielder6FC1Id, 
    @countMinFielder6FC1, 
    @countScoredGoalFielder6FC1, 
    @countAssistFielder6FC1, 
    @countScoredAutogoalFielder6FC1, 
    @countYellowCardFielder6FC1, 
    @countRedCardFielder6FC1, 
    @fielder7FC1Id, 
    @countMinFielder7FC1, 
    @countScoredGoalFielder7FC1, 
    @countAssistFielder7FC1, 
    @countScoredAutogoalFielder7FC1, 
    @countYellowCardFielder7FC1, 
    @countRedCardFielder7FC1,
	@fielder8FC1Id, 
    @countMinFielder8FC1, 
    @countScoredGoalFielder8FC1, 
    @countAssistFielder8FC1, 
    @countScoredAutogoalFielder8FC1, 
    @countYellowCardFielder8FC1, 
    @countRedCardFielder8FC1, 
    @fielder9FC1Id, 
    @countMinFielder9FC1, 
    @countScoredGoalFielder9FC1, 
    @countAssistFielder9FC1, 
    @countScoredAutogoalFielder9FC1, 
    @countYellowCardFielder9FC1, 
    @countRedCardFielder9FC1, 
    @fielder10FC1Id, 
    @countMinFielder10FC1, 
    @countScoredGoalFielder10FC1, 
    @countAssistFielder10FC1, 
    @countScoredAutogoalFielder10FC1, 
    @countYellowCardFielder10FC1, 
    @countRedCardFielder10FC1,
	@reserve1FC1Id, 
    @countMissedGoalReserveKeeper1FC1, 
    @countMinReserve1FC1, 
    @countScoredGoalReserve1FC1, 
    @countAssistReserve1FC1, 
    @countScoredAutogoalReserve1FC1, 
    @countYellowCardReserve1FC1, 
    @countRedCardReserve1FC1, 
    @reserve2FC1Id, 
    @countMissedGoalReserveKeeper2FC1, 
    @countMinReserve2FC1, 
    @countScoredGoalReserve2FC1, 
    @countAssistReserve2FC1, 
    @countScoredAutogoalReserve2FC1, 
    @countYellowCardReserve2FC1, 
    @countRedCardReserve2FC1, 
    @reserve3FC1Id, 
    @countMissedGoalReserveKeeper3FC1, 
    @countMinReserve3FC1, 
    @countScoredGoalReserve3FC1, 
    @countAssistReserve3FC1, 
    @countScoredAutogoalReserve3FC1, 
    @countYellowCardReserve3FC1, 
    @countRedCardReserve3FC1,
    @keeperFC2Id, 
    @countMinKeeperFC2, 
    @countMissedGoalKeeperFC2, 
    @countScoredGoalKeeperFC2, 
    @countScoredAutogoalKeeperFC2,
    @countAssistKeeperFC2, 
    @countYellowCardKeeperFC2, 
    @countRedCardKeeperFC2, 
    @fielder1FC2Id, 
    @countMinFielder1FC2, 
    @countScoredGoalFielder1FC2, 
    @countAssistFielder1FC2, 
    @countScoredAutogoalFielder1FC2, 
    @countYellowCardFielder1FC2, 
    @countRedCardFielder1FC2, 
    @fielder2FC2Id, 
    @countMinFielder2FC2, 
    @countScoredGoalFielder2FC2, 
    @countAssistFielder2FC2, 
    @countScoredAutogoalFielder2FC2, 
    @countYellowCardFielder2FC2, 
    @countRedCardFielder2FC2, 
    @fielder3FC2Id, 
    @countMinFielder3FC2, 
    @countScoredGoalFielder3FC2, 
    @countAssistFielder3FC2, 
    @countScoredAutogoalFielder3FC2, 
    @countYellowCardFielder3FC2, 
    @countRedCardFielder3FC2,
    @fielder4FC2Id, 
    @countMinFielder4FC2, 
    @countScoredGoalFielder4FC2, 
    @countAssistFielder4FC2, 
    @countScoredAutogoalFielder4FC2, 
    @countYellowCardFielder4FC2, 
    @countRedCardFielder4FC2, 
    @fielder5FC2Id, 
    @countMinFielder5FC2, 
    @countScoredGoalFielder5FC2, 
    @countAssistFielder5FC2, 
    @countScoredAutogoalFielder5FC2, 
    @countYellowCardFielder5FC2, 
    @countRedCardFielder5FC2, 
    @fielder6FC2Id, 
    @countMinFielder6FC2, 
    @countScoredGoalFielder6FC2, 
    @countAssistFielder6FC2, 
    @countScoredAutogoalFielder6FC2, 
    @countYellowCardFielder6FC2, 
    @countRedCardFielder6FC2, 
    @fielder7FC2Id, 
    @countMinFielder7FC2, 
    @countScoredGoalFielder7FC2, 
    @countAssistFielder7FC2, 
    @countScoredAutogoalFielder7FC2, 
    @countYellowCardFielder7FC2, 
    @countRedCardFielder7FC2, 
    @fielder8FC2Id, 
    @countMinFielder8FC2, 
    @countScoredGoalFielder8FC2, 
    @countAssistFielder8FC2, 
    @countScoredAutogoalFielder8FC2, 
    @countYellowCardFielder8FC2, 
    @countRedCardFielder8FC2, 
    @fielder9FC2Id, 
    @countMinFielder9FC2, 
    @countScoredGoalFielder9FC2, 
    @countAssistFielder9FC2, 
    @countScoredAutogoalFielder9FC2, 
    @countYellowCardFielder9FC2, 
    @countRedCardFielder9FC2, 
    @fielder10FC2Id, 
    @countMinFielder10FC2, 
    @countScoredGoalFielder10FC2, 
    @countAssistFielder10FC2, 
    @countScoredAutogoalFielder10FC2, 
    @countYellowCardFielder10FC2, 
    @countRedCardFielder10FC2, 
    @reserve1FC2Id, 
    @countMissedGoalReserveKeeper1FC2, 
    @countMinReserve1FC2, 
    @countScoredGoalReserve1FC2, 
    @countAssistReserve1FC2, 
    @countScoredAutogoalReserve1FC2, 
    @countYellowCardReserve1FC2, 
    @countRedCardReserve1FC2, 
    @reserve2FC2Id, 
    @countMissedGoalReserveKeeper2FC2, 
    @countMinReserve2FC2, 
    @countScoredGoalReserve2FC2, 
    @countAssistReserve2FC2, 
    @countScoredAutogoalReserve2FC2, 
    @countYellowCardReserve2FC2, 
    @countRedCardReserve2FC2, 
    @reserve3FC2Id, 
    @countMissedGoalReserveKeeper3FC2, 
    @countMinReserve3FC2, 
    @countScoredGoalReserve3FC2, 
    @countAssistReserve3FC2, 
    @countScoredAutogoalReserve3FC2, 
    @countYellowCardReserve3FC2, 
    @countRedCardReserve3FC2)
END;