CREATE PROCEDURE [dbo].[Update_Match]
	@id INT,
	@tournamentId INT,
	@chiefRefereeId INT,
	@leftLinesmanId INT,
	@rightLinesmanId INT,
	@reserveRefereeId INT,
	@varId INT,
	@varAssistantId INT,
	@fc1Id INT,
	@fc2Id INT,
	@countGoalsFC1 TINYINT,
	@countGoalsFC2 TINYINT,
	@coachFC1Id INT,
	@coachFC2Id INT,
	@keeperFC1Id INT,
	@countMinKeeperFC1 TINYINT,
	@countMissedGoalKeeperFC1 TINYINT,
	@countScoredGoalKeeperFC1 TINYINT,
	@countScoredAutogoalKeeperFC1 TINYINT,
	@countAssistKeeperFC1 TINYINT,
	@countYellowCardKeeperFC1 TINYINT,
	@countRedCardKeeperFC1 BIT,
	@fielder1FC1Id INT,
	@countMinFielder1FC1 TINYINT,
	@countScoredGoalFielder1FC1 TINYINT,
	@countAssistFielder1FC1 TINYINT,
	@countScoredAutogoalFielder1FC1 TINYINT,
	@countYellowCardFielder1FC1 TINYINT,
	@countRedCardFielder1FC1 BIT,
	@fielder2FC1Id INT,
	@countMinFielder2FC1 TINYINT,
	@countScoredGoalFielder2FC1 TINYINT,
	@countAssistFielder2FC1 TINYINT,
	@countScoredAutogoalFielder2FC1 TINYINT,
	@countYellowCardFielder2FC1 TINYINT,
	@countRedCardFielder2FC1 BIT,
	@fielder3FC1Id INT,
	@countMinFielder3FC1 TINYINT,
	@countScoredGoalFielder3FC1 TINYINT,
	@countAssistFielder3FC1 TINYINT,
	@countScoredAutogoalFielder3FC1 TINYINT,
	@countYellowCardFielder3FC1 TINYINT,
	@countRedCardFielder3FC1 BIT,
	@fielder4FC1Id INT, 
    @countMinFielder4FC1 TINYINT, 
    @countScoredGoalFielder4FC1 TINYINT, 
    @countAssistFielder4FC1 TINYINT, 
    @countScoredAutogoalFielder4FC1 TINYINT, 
    @countYellowCardFielder4FC1 TINYINT, 
    @countRedCardFielder4FC1 BIT, 
	@fielder5FC1Id INT, 
    @countMinFielder5FC1 TINYINT, 
    @countScoredGoalFielder5FC1 TINYINT, 
    @countAssistFielder5FC1 TINYINT, 
    @countScoredAutogoalFielder5FC1 TINYINT, 
    @countYellowCardFielder5FC1 TINYINT, 
    @countRedCardFielder5FC1 BIT, 
    @fielder6FC1Id INT, 
    @countMinFielder6FC1 TINYINT, 
    @countScoredGoalFielder6FC1 TINYINT, 
    @countAssistFielder6FC1 TINYINT, 
    @countScoredAutogoalFielder6FC1 TINYINT, 
    @countYellowCardFielder6FC1 TINYINT, 
    @countRedCardFielder6FC1 BIT, 
    @fielder7FC1Id INT, 
    @countMinFielder7FC1 TINYINT, 
    @countScoredGoalFielder7FC1 TINYINT, 
    @countAssistFielder7FC1 TINYINT, 
    @countScoredAutogoalFielder7FC1 TINYINT, 
    @countYellowCardFielder7FC1 TINYINT, 
    @countRedCardFielder7FC1 BIT,
	@fielder8FC1Id INT, 
    @countMinFielder8FC1 TINYINT, 
    @countScoredGoalFielder8FC1 TINYINT, 
    @countAssistFielder8FC1 TINYINT, 
    @countScoredAutogoalFielder8FC1 TINYINT, 
    @countYellowCardFielder8FC1 TINYINT, 
    @countRedCardFielder8FC1 BIT, 
    @fielder9FC1Id INT, 
    @countMinFielder9FC1 TINYINT, 
    @countScoredGoalFielder9FC1 TINYINT, 
    @countAssistFielder9FC1 TINYINT, 
    @countScoredAutogoalFielder9FC1 TINYINT, 
    @countYellowCardFielder9FC1 TINYINT, 
    @countRedCardFielder9FC1 BIT, 
    @fielder10FC1Id INT, 
    @countMinFielder10FC1 TINYINT, 
    @countScoredGoalFielder10FC1 TINYINT, 
    @countAssistFielder10FC1 TINYINT, 
    @countScoredAutogoalFielder10FC1 TINYINT, 
    @countYellowCardFielder10FC1 TINYINT, 
    @countRedCardFielder10FC1 BIT,
	@reserve1FC1Id INT, 
    @countMissedGoalReserveKeeper1FC1 TINYINT, 
    @countMinReserve1FC1 TINYINT, 
    @countScoredGoalReserve1FC1 TINYINT, 
    @countAssistReserve1FC1 TINYINT, 
    @countScoredAutogoalReserve1FC1 TINYINT, 
    @countYellowCardReserve1FC1 TINYINT, 
    @countRedCardReserve1FC1 BIT, 
    @reserve2FC1Id INT, 
    @countMissedGoalReserveKeeper2FC1 TINYINT, 
    @countMinReserve2FC1 TINYINT, 
    @countScoredGoalReserve2FC1 TINYINT, 
    @countAssistReserve2FC1 TINYINT, 
    @countScoredAutogoalReserve2FC1 TINYINT, 
    @countYellowCardReserve2FC1 TINYINT, 
    @countRedCardReserve2FC1 BIT, 
    @reserve3FC1Id INT, 
    @countMissedGoalReserveKeeper3FC1 TINYINT, 
    @countMinReserve3FC1 TINYINT, 
    @countScoredGoalReserve3FC1 TINYINT, 
    @countAssistReserve3FC1 TINYINT, 
    @countScoredAutogoalReserve3FC1 TINYINT, 
    @countYellowCardReserve3FC1 TINYINT, 
    @countRedCardReserve3FC1 BIT,
    @keeperFC2Id INT, 
    @countMinKeeperFC2 TINYINT, 
    @countMissedGoalKeeperFC2 TINYINT, 
    @countScoredGoalKeeperFC2 TINYINT, 
    @countScoredAutogoalKeeperFC2 TINYINT,
    @countAssistKeeperFC2 TINYINT, 
    @countYellowCardKeeperFC2 TINYINT, 
    @countRedCardKeeperFC2 BIT, 
    @fielder1FC2Id INT, 
    @countMinFielder1FC2 TINYINT, 
    @countScoredGoalFielder1FC2 TINYINT, 
    @countAssistFielder1FC2 TINYINT, 
    @countScoredAutogoalFielder1FC2 TINYINT, 
    @countYellowCardFielder1FC2 TINYINT, 
    @countRedCardFielder1FC2 BIT, 
    @fielder2FC2Id INT, 
    @countMinFielder2FC2 TINYINT, 
    @countScoredGoalFielder2FC2 TINYINT, 
    @countAssistFielder2FC2 TINYINT, 
    @countScoredAutogoalFielder2FC2 TINYINT, 
    @countYellowCardFielder2FC2 TINYINT, 
    @countRedCardFielder2FC2 BIT, 
    @fielder3FC2Id INT, 
    @countMinFielder3FC2 TINYINT, 
    @countScoredGoalFielder3FC2 TINYINT, 
    @countAssistFielder3FC2 TINYINT, 
    @countScoredAutogoalFielder3FC2 TINYINT, 
    @countYellowCardFielder3FC2 TINYINT, 
    @countRedCardFielder3FC2 BIT,
    @fielder4FC2Id INT, 
    @countMinFielder4FC2 TINYINT, 
    @countScoredGoalFielder4FC2 TINYINT, 
    @countAssistFielder4FC2 TINYINT, 
    @countScoredAutogoalFielder4FC2 TINYINT, 
    @countYellowCardFielder4FC2 TINYINT, 
    @countRedCardFielder4FC2 BIT, 
    @fielder5FC2Id INT, 
    @countMinFielder5FC2 TINYINT, 
    @countScoredGoalFielder5FC2 TINYINT, 
    @countAssistFielder5FC2 TINYINT, 
    @countScoredAutogoalFielder5FC2 TINYINT, 
    @countYellowCardFielder5FC2 TINYINT, 
    @countRedCardFielder5FC2 BIT, 
    @fielder6FC2Id INT, 
    @countMinFielder6FC2 TINYINT, 
    @countScoredGoalFielder6FC2 TINYINT, 
    @countAssistFielder6FC2 TINYINT, 
    @countScoredAutogoalFielder6FC2 TINYINT, 
    @countYellowCardFielder6FC2 TINYINT, 
    @countRedCardFielder6FC2 BIT, 
    @fielder7FC2Id INT, 
    @countMinFielder7FC2 TINYINT, 
    @countScoredGoalFielder7FC2 TINYINT, 
    @countAssistFielder7FC2 TINYINT, 
    @countScoredAutogoalFielder7FC2 TINYINT, 
    @countYellowCardFielder7FC2 TINYINT, 
    @countRedCardFielder7FC2 BIT, 
    @fielder8FC2Id INT, 
    @countMinFielder8FC2 TINYINT, 
    @countScoredGoalFielder8FC2 TINYINT, 
    @countAssistFielder8FC2 TINYINT, 
    @countScoredAutogoalFielder8FC2 TINYINT, 
    @countYellowCardFielder8FC2 TINYINT, 
    @countRedCardFielder8FC2 BIT, 
    @fielder9FC2Id INT, 
    @countMinFielder9FC2 TINYINT, 
    @countScoredGoalFielder9FC2 TINYINT, 
    @countAssistFielder9FC2 TINYINT, 
    @countScoredAutogoalFielder9FC2 TINYINT, 
    @countYellowCardFielder9FC2 TINYINT, 
    @countRedCardFielder9FC2 BIT, 
    @fielder10FC2Id INT, 
    @countMinFielder10FC2 TINYINT, 
    @countScoredGoalFielder10FC2 TINYINT, 
    @countAssistFielder10FC2 TINYINT, 
    @countScoredAutogoalFielder10FC2 TINYINT, 
    @countYellowCardFielder10FC2 TINYINT, 
    @countRedCardFielder10FC2 BIT, 
    @reserve1FC2Id INT, 
    @countMissedGoalReserveKeeper1FC2 TINYINT, 
    @countMinReserve1FC2 TINYINT, 
    @countScoredGoalReserve1FC2 TINYINT, 
    @countAssistReserve1FC2 TINYINT, 
    @countScoredAutogoalReserve1FC2 TINYINT, 
    @countYellowCardReserve1FC2 TINYINT, 
    @countRedCardReserve1FC2 BIT, 
    @reserve2FC2Id INT, 
    @countMissedGoalReserveKeeper2FC2 TINYINT, 
    @countMinReserve2FC2 TINYINT, 
    @countScoredGoalReserve2FC2 TINYINT, 
    @countAssistReserve2FC2 TINYINT, 
    @countScoredAutogoalReserve2FC2 TINYINT, 
    @countYellowCardReserve2FC2 TINYINT, 
    @countRedCardReserve2FC2 BIT, 
    @reserve3FC2Id INT, 
    @countMissedGoalReserveKeeper3FC2 TINYINT, 
    @countMinReserve3FC2 TINYINT, 
    @countScoredGoalReserve3FC2 TINYINT, 
    @countAssistReserve3FC2 TINYINT, 
    @countScoredAutogoalReserve3FC2 TINYINT, 
    @countYellowCardReserve3FC2 TINYINT, 
    @countRedCardReserve3FC2 BIT 
AS
BEGIN
	UPDATE Matches
	SET TournamentId = @tournamentId, 
        ChiefRefereeId = @chiefRefereeId, 
        LeftLinesmanId = @leftLinesmanId, 
        RightLinesmanId = @rightLinesmanId, 
        ReserveRefereeId = @reserveRefereeId, 
        VARId = @varId, 
        VARAssistantId = @varAssistantId, 
        FC1Id = @fc1Id, 
        FC2Id = @fc2Id, 
        CountGoalsFC1 = @countGoalsFC1, 
        CountGoalsFC2 = @countGoalsFC2, 
        CoachFC1Id = @coachFC1Id, 
        CoachFC2Id = @coachFC2Id, 
        KeeperFC1Id = @keeperFC1Id, 
        CountMinKeeperFC1 = @countMinKeeperFC1, 
        CountMissedGoalKeeperFC1 = @countMissedGoalKeeperFC1, 
        CountScoredGoalKeeperFC1 = @countScoredGoalKeeperFC1, 
        CountScoredAutogoalKeeperFC1 = @countScoredAutogoalKeeperFC1,
        CountAssistKeeperFC1 = @countAssistKeeperFC1, 
        CountYellowCardKeeperFC1 = @countYellowCardKeeperFC1, 
        CountRedCardKeeperFC1 = @countRedCardKeeperFC1, 
        Fielder1FC1Id = @fielder1FC1Id, 
        CountMinFielder1FC1 = @countMinFielder1FC1, 
        CountScoredGoalFielder1FC1 = @countScoredGoalFielder1FC1, 
        CountAssistFielder1FC1 = @countAssistFielder1FC1, 
        CountScoredAutogoalFielder1FC1 = @countScoredAutogoalFielder1FC1, 
        CountYellowCardFielder1FC1 = @countYellowCardFielder1FC1, 
        CountRedCardFielder1FC1 = @countRedCardFielder1FC1, 
        Fielder2FC1Id = @fielder2FC1Id, 
        CountMinFielder2FC1 = @countMinFielder2FC1, 
        CountScoredGoalFielder2FC1 = @countScoredGoalFielder2FC1, 
        CountAssistFielder2FC1 = @countAssistFielder2FC1, 
        CountScoredAutogoalFielder2FC1 = @countScoredAutogoalFielder2FC1, 
        CountYellowCardFielder2FC1 = @countYellowCardFielder2FC1, 
        CountRedCardFielder2FC1 = @countRedCardFielder2FC1, 
        Fielder3FC1Id = @fielder3FC1Id, 
        CountMinFielder3FC1 = @countMinFielder3FC1, 
        CountScoredGoalFielder3FC1 = @countScoredGoalFielder3FC1, 
        CountAssistFielder3FC1 = @countAssistFielder3FC1, 
        CountScoredAutogoalFielder3FC1 = @countScoredAutogoalFielder3FC1, 
        CountYellowCardFielder3FC1 = @countYellowCardFielder3FC1, 
        CountRedCardFielder3FC1 = @countRedCardFielder3FC1, 
        Fielder4FC1Id = @fielder4FC1Id, 
        CountMinFielder4FC1 = @countMinFielder4FC1, 
        CountScoredGoalFielder4FC1 = @countScoredGoalFielder4FC1, 
        CountAssistFielder4FC1 = @countAssistFielder4FC1, 
        CountScoredAutogoalFielder4FC1 = @countScoredAutogoalFielder4FC1, 
        CountYellowCardFielder4FC1 = @countYellowCardFielder4FC1, 
        CountRedCardFielder4FC1 = @countRedCardFielder4FC1, 
        Fielder5FC1Id = @fielder5FC1Id, 
        CountMinFielder5FC1 = @countMinFielder5FC1, 
        CountScoredGoalFielder5FC1 = @countScoredGoalFielder5FC1, 
        CountAssistFielder5FC1 = @countAssistFielder5FC1, 
        CountScoredAutogoalFielder5FC1 = @countScoredAutogoalFielder5FC1, 
        CountYellowCardFielder5FC1 = @countYellowCardFielder5FC1, 
        CountRedCardFielder5FC1 = @countRedCardFielder5FC1, 
        Fielder6FC1Id = @fielder6FC1Id, 
        CountMinFielder6FC1 = @countMinFielder6FC1, 
        CountScoredGoalFielder6FC1 = @countScoredGoalFielder6FC1, 
        CountAssistFielder6FC1 = @countAssistFielder6FC1, 
        CountScoredAutogoalFielder6FC1 = @countScoredAutogoalFielder6FC1, 
        CountYellowCardFielder6FC1 = @countYellowCardFielder6FC1, 
        CountRedCardFielder6FC1 = @countRedCardFielder6FC1, 
        Fielder7FC1Id = @fielder7FC1Id, 
        CountMinFielder7FC1 = @countMinFielder7FC1, 
        CountScoredGoalFielder7FC1 = @countScoredGoalFielder7FC1, 
        CountAssistFielder7FC1 = @countAssistFielder7FC1, 
        CountScoredAutogoalFielder7FC1 = @countScoredAutogoalFielder7FC1, 
        CountYellowCardFielder7FC1 = @countYellowCardFielder7FC1, 
        CountRedCardFielder7FC1 = @countRedCardFielder7FC1, 
        Fielder8FC1Id = @fielder8FC1Id, 
        CountMinFielder8FC1 = @countMinFielder8FC1, 
        CountScoredGoalFielder8FC1 = @countScoredGoalFielder8FC1, 
        CountAssistFielder8FC1 = @countAssistFielder8FC1, 
        CountScoredAutogoalFielder8FC1 = @countScoredAutogoalFielder8FC1, 
        CountYellowCardFielder8FC1 = @countYellowCardFielder8FC1, 
        CountRedCardFielder8FC1 = @countRedCardFielder8FC1, 
        Fielder9FC1Id = @fielder9FC1Id, 
        CountMinFielder9FC1 = @countMinFielder9FC1, 
        CountScoredGoalFielder9FC1 = @countScoredGoalFielder9FC1, 
        CountAssistFielder9FC1 = @countAssistFielder9FC1, 
        CountScoredAutogoalFielder9FC1 = @countScoredAutogoalFielder9FC1, 
        CountYellowCardFielder9FC1 = @countYellowCardFielder9FC1, 
        CountRedCardFielder9FC1 = @countRedCardFielder9FC1, 
        Fielder10FC1Id = @fielder10FC1Id, 
        CountMinFielder10FC1 = @countMinFielder10FC1, 
        CountScoredGoalFielder10FC1 = @countScoredGoalFielder10FC1, 
        CountAssistFielder10FC1 = @countAssistFielder10FC1, 
        CountScoredAutogoalFielder10FC1 = @countScoredAutogoalFielder10FC1, 
        CountYellowCardFielder10FC1 = @countYellowCardFielder10FC1, 
        CountRedCardFielder10FC1 = @countRedCardFielder10FC1, 
        Reserve1FC1Id = @reserve1FC1Id, 
        CountMissedGoalReserveKeeper1FC1 = @countMissedGoalReserveKeeper1FC1, 
        CountMinReserve1FC1 = @countMinReserve1FC1, 
        CountScoredGoalReserve1FC1 = @countScoredGoalReserve1FC1, 
        CountAssistReserve1FC1 = @countAssistReserve1FC1, 
        CountScoredAutogoalReserve1FC1 = @countScoredAutogoalReserve1FC1, 
        CountYellowCardReserve1FC1 = @countYellowCardReserve1FC1, 
        CountRedCardReserve1FC1 = @countRedCardReserve1FC1, 
        Reserve2FC1Id = @reserve2FC1Id, 
        CountMissedGoalReserveKeeper2FC1 = @countMissedGoalReserveKeeper2FC1, 
        CountMinReserve2FC1 = @countMinReserve2FC1, 
        CountScoredGoalReserve2FC1 = @countScoredGoalReserve2FC1, 
        CountAssistReserve2FC1 = @countAssistReserve2FC1, 
        CountScoredAutogoalReserve2FC1 = @countScoredAutogoalReserve2FC1, 
        CountYellowCardReserve2FC1 = @countYellowCardReserve2FC1, 
        CountRedCardReserve2FC1 = @countRedCardReserve2FC1, 
        Reserve3FC1Id = @reserve3FC1Id, 
        CountMissedGoalReserveKeeper3FC1 = @countMissedGoalReserveKeeper3FC1, 
        CountMinReserve3FC1 = @countMinReserve3FC1, 
        CountScoredGoalReserve3FC1 = @countScoredGoalReserve3FC1, 
        CountAssistReserve3FC1 = @countAssistReserve3FC1, 
        CountScoredAutogoalReserve3FC1 = @countScoredAutogoalReserve3FC1, 
        CountYellowCardReserve3FC1 = @countYellowCardReserve3FC1, 
        CountRedCardReserve3FC1 = @countRedCardReserve3FC1, 
        KeeperFC2Id = @keeperFC2Id, 
        CountMinKeeperFC2 = @countMinKeeperFC2, 
        CountMissedGoalKeeperFC2 = @countMissedGoalKeeperFC2, 
        CountScoredGoalKeeperFC2 = @countScoredGoalKeeperFC2, 
        CountScoredAutogoalKeeperFC2 = @countScoredAutogoalKeeperFC2,
        CountAssistKeeperFC2 = @countAssistKeeperFC2, 
        CountYellowCardKeeperFC2 = @countYellowCardKeeperFC2, 
        CountRedCardKeeperFC2 = @countRedCardKeeperFC2, 
        Fielder1FC2Id = @fielder1FC2Id, 
        CountMinFielder1FC2 = @countMinFielder1FC2, 
        CountScoredGoalFielder1FC2 = @countScoredGoalFielder1FC2, 
        CountAssistFielder1FC2 = @countAssistFielder1FC2, 
        CountScoredAutogoalFielder1FC2 = @countScoredAutogoalFielder1FC2, 
        CountYellowCardFielder1FC2 = @countYellowCardFielder1FC2, 
        CountRedCardFielder1FC2 = @countRedCardFielder1FC2, 
        Fielder2FC2Id = @fielder2FC2Id, 
        CountMinFielder2FC2 = @countMinFielder2FC2, 
        CountScoredGoalFielder2FC2 = @countScoredGoalFielder2FC2, 
        CountAssistFielder2FC2 = @countAssistFielder2FC2, 
        CountScoredAutogoalFielder2FC2 = @countScoredAutogoalFielder2FC2, 
        CountYellowCardFielder2FC2 = @countYellowCardFielder2FC2, 
        CountRedCardFielder2FC2 = @countRedCardFielder2FC2, 
        Fielder3FC2Id = @fielder3FC2Id, 
        CountMinFielder3FC2 = @countMinFielder3FC2, 
        CountScoredGoalFielder3FC2 = @countScoredGoalFielder3FC2, 
        CountAssistFielder3FC2 = @countAssistFielder3FC2, 
        CountScoredAutogoalFielder3FC2 = @countScoredAutogoalFielder3FC2, 
        CountYellowCardFielder3FC2 = @countYellowCardFielder3FC2, 
        CountRedCardFielder3FC2 = @countRedCardFielder3FC2, 
        Fielder4FC2Id = @fielder4FC2Id, 
        CountMinFielder4FC2 = @countMinFielder4FC2, 
        CountScoredGoalFielder4FC2 = @countScoredGoalFielder4FC2, 
        CountAssistFielder4FC2 = @countAssistFielder4FC2, 
        CountScoredAutogoalFielder4FC2 = @countScoredAutogoalFielder4FC2, 
        CountYellowCardFielder4FC2 = @countYellowCardFielder4FC2, 
        CountRedCardFielder4FC2 = @countRedCardFielder4FC2, 
        Fielder5FC2Id = @fielder5FC2Id, 
        CountMinFielder5FC2 = @countMinFielder5FC2, 
        CountScoredGoalFielder5FC2 = @countScoredGoalFielder5FC2, 
        CountAssistFielder5FC2 = @countAssistFielder5FC2, 
        CountScoredAutogoalFielder5FC2 = @countScoredAutogoalFielder5FC2, 
        CountYellowCardFielder5FC2 = @countYellowCardFielder5FC2, 
        CountRedCardFielder5FC2 = @countRedCardFielder5FC2, 
        Fielder6FC2Id = @fielder6FC2Id, 
        CountMinFielder6FC2 = @countMinFielder6FC2, 
        CountScoredGoalFielder6FC2 = @countScoredGoalFielder6FC2, 
        CountAssistFielder6FC2 = @countAssistFielder6FC2, 
        CountScoredAutogoalFielder6FC2 = @countScoredAutogoalFielder6FC2, 
        CountYellowCardFielder6FC2 = @countYellowCardFielder6FC2, 
        CountRedCardFielder6FC2 = @countRedCardFielder6FC2, 
        Fielder7FC2Id = @fielder7FC2Id, 
        CountMinFielder7FC2 = @countMinFielder7FC2, 
        CountScoredGoalFielder7FC2 = @countScoredGoalFielder7FC2, 
        CountAssistFielder7FC2 = @countAssistFielder7FC2, 
        CountScoredAutogoalFielder7FC2 = @countScoredAutogoalFielder7FC2, 
        CountYellowCardFielder7FC2 = @countYellowCardFielder7FC2, 
        CountRedCardFielder7FC2 = @countRedCardFielder7FC2, 
        Fielder8FC2Id = @fielder8FC2Id, 
        CountMinFielder8FC2 = @countMinFielder8FC2, 
        CountScoredGoalFielder8FC2 = @countScoredGoalFielder8FC2, 
        CountAssistFielder8FC2 = @countAssistFielder8FC2, 
        CountScoredAutogoalFielder8FC2 = @countScoredAutogoalFielder8FC2, 
        CountYellowCardFielder8FC2 = @countYellowCardFielder8FC2, 
        CountRedCardFielder8FC2 = @countRedCardFielder8FC2, 
        Fielder9FC2Id = @fielder9FC2Id, 
        CountMinFielder9FC2 = @countMinFielder9FC2, 
        CountScoredGoalFielder9FC2 = @countScoredGoalFielder9FC2, 
        CountAssistFielder9FC2 = @countAssistFielder9FC2, 
        CountScoredAutogoalFielder9FC2 = @countScoredAutogoalFielder9FC2, 
        CountYellowCardFielder9FC2 = @countYellowCardFielder9FC2, 
        CountRedCardFielder9FC2 = @countRedCardFielder9FC2, 
        Fielder10FC2Id = @fielder10FC2Id, 
        CountMinFielder10FC2 = @countMinFielder10FC2, 
        CountScoredGoalFielder10FC2 = @countScoredGoalFielder10FC2, 
        CountAssistFielder10FC2 = @countAssistFielder10FC2, 
        CountScoredAutogoalFielder10FC2 = @countScoredAutogoalFielder10FC2, 
        CountYellowCardFielder10FC2 = @countYellowCardFielder10FC2, 
        CountRedCardFielder10FC2 = @countRedCardFielder10FC2, 
        Reserve1FC2Id = @reserve1FC2Id, 
        CountMissedGoalReserveKeeper1FC2 = @countMissedGoalReserveKeeper1FC2, 
        CountMinReserve1FC2 = @countMinReserve1FC2, 
        CountScoredGoalReserve1FC2 = @countScoredGoalReserve1FC2, 
        CountAssistReserve1FC2 = @countAssistReserve1FC2, 
        CountScoredAutogoalReserve1FC2 = @countScoredAutogoalReserve1FC2, 
        CountYellowCardReserve1FC2 = @countYellowCardReserve1FC2, 
        CountRedCardReserve1FC2 = @countRedCardReserve1FC2, 
        Reserve2FC2Id = @reserve2FC2Id, 
        CountMissedGoalReserveKeeper2FC2 = @countMissedGoalReserveKeeper2FC2, 
        CountMinReserve2FC2 = @countMinReserve2FC2, 
        CountScoredGoalReserve2FC2 = @countScoredGoalReserve2FC2, 
        CountAssistReserve2FC2 = @countAssistReserve2FC2, 
        CountScoredAutogoalReserve2FC2 = @countScoredAutogoalReserve2FC2, 
        CountYellowCardReserve2FC2 = @countYellowCardReserve2FC2, 
        CountRedCardReserve2FC2 = @countRedCardReserve2FC2, 
        Reserve3FC2Id = @reserve3FC2Id, 
        CountMissedGoalReserveKeeper3FC2 = @countMissedGoalReserveKeeper3FC2, 
        CountMinReserve3FC2 = @countMinReserve3FC2, 
        CountScoredGoalReserve3FC2 = @countScoredGoalReserve3FC2, 
        CountAssistReserve3FC2 = @countAssistReserve3FC2, 
        CountScoredAutogoalReserve3FC2 = @countScoredAutogoalReserve3FC2, 
        CountYellowCardReserve3FC2 = @countYellowCardReserve3FC2, 
        CountRedCardReserve3FC2 = @countRedCardReserve3FC2 
    WHERE MatchId = @id
END;